### ISSUE TITLE
[chore] Update gherkin and messages dependencies

### ISSUE THREAD

**Issue by aaronc** [regen-network/gocuke#21]
We're at gherkin/v27 and message/v21 and the latest releases are https://pkg.go.dev/github.com/cucumber/gherkin/go/v27 and https://pkg.go.dev/github.com/cucumber/messages/go/v22.

**Comment by 0xste** [comment]
Would be nice to roll this into the CI discussions and use dependabot for these kinds of issues

**Comment by aaronc** [comment]
For minor versions dependabot would be nice. Seems like the cucumber deps often do major releases although I'm not sure how often the API is actually breaking with these
