### ISSUE TITLE
[chore] Release v1.0

### ISSUE THREAD

**Issue by aaronc** [regen-network/gocuke#24]
We should follow go semantic versioning. If the current API seems stable enough and good enough for now, we should tag this as v1.0 and then do v2, v3, etc if any breaking changes are needed.

**Comment by 0xste** [comment]
Happy to go ahead with a `v1.0.0` from current head of main (been running most of my stuff against this for the past weeks)

**Comment by aaronc** [comment]
Sounds good. I can go ahead and tag v1.0.0.

Do you think it's realistic to finish #17 so that we can automatic releases and CHANGELOGs?

**Comment by aaronc** [comment]
Closing this as done.
