### ISSUE TITLE
Tests are not actually parallel by default

### ISSUE THREAD

**Issue by dgunay** [regen-network/gocuke#32]
The docs say that tests are parallel by default, but `Runner.parallel` is never initialized to `true` anywhere in the codebase that I can find. We noticed that changing the code to do so sped our tests up a lot.

https://github.com/regen-network/gocuke/blob/8921eaed4a6dc3104f000cb4636da0d927b6cc3b/runner.go#L62

**Comment by aaronc** [comment]
Thanks for catching this error @dgunay ! Would you be able to push a small PR to fix it?

**Comment by dgunay** [comment]
> Thanks for catching this error @dgunay ! Would you be able to push a small PR to fix it?

Sure: #33
